apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: risk
  name: risk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: risk
  strategy: {}
  template:
    metadata:
      labels:
        app: risk
    spec:
      containers:
        - image: localhost:5001/risk:1.3.0
          name: risk
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /risks/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /risks/health
              port: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-password
            - name: POSTGRES_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres_address
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: risk-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: risk
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
